### ISSUE TITLE
There is no server!

### ISSUE THREAD

**Issue by pl608** [dovegaming/dovewebsite#11]
**Is your feature request related to a problem? Please describe.**
there doesnt seem to be a server, minetest or minecraft

**Describe the solution you'd like**
make a server

**Describe alternatives you've considered**
ig doent make a server :)

**Additional context**
can it be minetest as i dont have minecraft(nor do i foresee getting it in the future)

**Comment by TechDudie** [comment]
There is a server
However, it is a Minecraft one, and it isn’t up all the time, dove1234 manages it
Im responsible for the minetest server

**Comment by pl608** [comment]
where is the minetest server :)

**Comment by TechDudie** [comment]
In the ground, literally

the materials will be mined
The computer will be manufactured
I will get that computer
And i will run that server

the server is in the ground

**Comment by TechDudie** [comment]
Lol

**Comment by pl608** [comment]
k
