### ISSUE TITLE
Better Font

### ISSUE THREAD

**Issue by TechDudie** [dovegaming/dovewebsite#2]
Personally, I like the original font, but @pl608 suggests another font.

How to resolve: 
* Add a font setting

To-do:
- [x] Add a font setting

**Comment by pl608** [comment]
no not that i dont like it, it just doesnt work for some things.
it looks perfectly nice for the title and the status but it is almost (not quite) unreadable in some cases
i can show you simple way to resolve this issue

**Comment by pl608** [comment]
it looks perfectly nice for the title and the status but it is almost (not quite) unreadable in some cases

**Comment by pl608** [comment]
i can show you  simple way to resolve this issue

**Comment by pl608** [comment]
and i also need to condence all my comments into one bigg comment.......

**Comment by TechDudie** [comment]
ok thats appreciated
I put them together for u :)

**Comment by pl608** [comment]
thx :)
btw what do you think of the changes?

**Comment by TechDudie** [comment]
Merged!
