### ISSUE TITLE
about.html broken

### ISSUE THREAD

**Issue by TechDudie** [dovegaming/dovewebsite#7]
**Describe the bug**
about.html is broken

**To Reproduce**
1. Go to about.html
2. LOOK

**Expected behavior**
A staggered grid should appear with the members and their roles.

**Comment by pl608** [comment]
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to about.html
> 
>     2. LOOK


haha ok ill try to help you fix(just looks funny

edit: btw i looked and it looks fine, dont really know what the problem is or if you fixed it or not

**Comment by pl608** [comment]
_~~(though the black looks really bad)~~_

**Comment by TechDudie** [comment]
> > **To Reproduce** Steps to reproduce the behavior:
> > ```
> > 1. Go to about.html
> > 
> > 2. LOOK
> > ```
> 
> haha ok ill try to help you fix(just looks funny
> 
> edit: btw i looked and it looks fine, dont really know what the problem is or if you fixed it or not

i fixed it already ah now ic 
lol 😝
